### ISSUE TITLE
Key file mismatch or crypt14 file is corrupt.

### ISSUE THREAD

**Issue by mrmc-mc** [ElDavoo/WhatsApp-Crypt14-Decrypter#3]
Whatsapp version : 2.21.23.23
Key file and db file are correct

**Comment by ElDavoo** [comment]
Can you show me the headers of the db file please?

**Comment by needs-coffee** [comment]
I also found the same issue, however i used another crypt14 file from another backup (created with a previous whatsapp version) and it decrypted with no errors. Do you need the headers of the encrypted or decrypted db file?

**Comment by ElDavoo** [comment]
i should only need encrypted, but it doesn't hurt if you send decrypted too

**Comment by ElDavoo** [comment]
Hello @needs-coffee @mrmc-mc , the script has been overhauled and it should now decrypt your files. Please report the results. Happy NY :)
