### ISSUE TITLE
Getting a invalid type error with python3 when running script

### ISSUE THREAD

**Issue by ammadanjumch** [ElDavoo/WhatsApp-Crypt14-Decrypter#4]
% python3 ./WhatsApp-Crypt14-Decrypter/decrypt14.py msgstore.db.crypt14 msgstore.db
Traceback (most recent call last):
  File "./WhatsApp-Crypt14-Decrypter/decrypt14.py", line 151, in <module>
    def get_t1_and_key(key_file_stream) -> tuple[bytes, bytes]:
TypeError: 'type' object is not subscriptable

**Comment by ElDavoo** [comment]
wihch python version are you using?

**Comment by ElDavoo** [comment]
I guess you are using python 3.8 or less. I will now make an update to make the script compatible with python 3.7+ :)

**Comment by ammadanjumch** [comment]
@ElDavoo ahh yeah that was it. Lets see how far that takes me now 🍡
