### ISSUE TITLE
crypt15 decryption support

### ISSUE THREAD

**Issue by ElDavoo** [ElDavoo/WhatsApp-Crypt14-Decrypter#7]
I just noticed my backup files are .crypt15

**Comment by aldennisa15** [comment]
Which version of WhatsApp is producing crypt15 backups? (Just so can avoid upgrading, for now at least.) v2.22.3.77 is still producing crypt14.

**Comment by ElDavoo** [comment]
Don't enable end to end encrypted backups.

**Comment by ElDavoo** [comment]
It is for now available in beta versions and it is completely optional at the moment, you have to manually enable it

**Comment by ElDavoo** [comment]
Gotcha!
![image](https://user-images.githubusercontent.com/7345120/154365036-2f3edb60-63e2-4690-9621-9f9660222156.png)

**Comment by aldennisa15** [comment]
👏 good work! do crypt15 backups still use the same keyfile as crypt14 did then?

**Comment by ElDavoo** [comment]
No. You will need a different keyfile, which is called **encrypted_backup.key**

**Comment by SoloSpam69** [comment]
Where I can search the "encrypted_backup.key" file???
